### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Floppy**

### CODE REVIEW

**Comment by Floppy** [comment]
The new dependency on `charlock-holmes` breaks Heroku installs because of missing `libicu`. There are some options here: https://stackoverflow.com/questions/18926574/how-to-install-charlock-holmes-dependency-libicu-dev-on-heroku

**Comment by Floppy** [comment]
The Heroku buildpack at https://github.com/donnykurnia/heroku-buildpack-ruby looks like it will do the job, and is nicely kept up to date (thanks @donnykurnia!). I'll give it a go later on.

**Comment by Floppy** [comment]
And we can add the buildpacks in the `app.json`. I don't know if this will affect existing deployed apps though, which is a faff.

**Comment by Floppy** [comment]
I tried using the `heroku-16` stack, but to no avail. I need to look at this more, but in the meantime I've rolled this PR back to just updating rails.

**Comment by donnykurnia** [comment]
@Floppy I got mentioned above and I want to share a thing related with `charlock_holmes` gem. My project no longer using this gem, because we switch to using Ruby 2.x encoding.

Here is the sample of code written by Piotr Macuk <piotr@macuk.pl>

`input.to_s.encode('UTF-8', invalid: :replace, undef: :replace)`

Hope it help you in this project so you can easily deploy it to Heroku without the needs of `charlock_holmes` gem.

**Comment by Floppy** [comment]
Thanks @donnykurnia - we're not using charlock_holmes directly, it's deep down in the dependency stack, but I'll see if I can make any progress using your suggestion. Thanks!

**Pull request merged**
